SAPDUAZ2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apps.docente.views import Index
from django.contrib.auth.views import LogoutView

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('logout', LogoutView.as_view(), name='logout'),
                  path('docente/', include('apps.docente.urls', namespace='docente')),
                  path('nivel/', include('apps.nivel.urls', namespace='nivel')),
                  path('base/', include('apps.base.urls', namespace='base')),
                  path('index', Index.as_view(), name='index')
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/base/urls.py
from django.urls import path
from apps.base.views import base_list,nueva_base,docente_base_list


app_name='base'
urlpatterns = [
    path('listar',base_list,name='base_listar'),
    path('bases/nuevo/<id>',nueva_base,name='base_nueva'),
    path('historial/<id>',docente_base_list, name='historial_base'),
]

apps/docente/urls.py
from django.urls import path
from apps.docente import views

app_name = 'docente'
urlpatterns = [
    path('listar', views.ListaDocentes.as_view(), name='docente_listar'),
    path('activar/<id>', views.docente_activate, name='docente_activar'),
    path('nuevo/', views.NuevoDocente.as_view(), name='docente_nuevo'),
    path('gradonuevo/<id>', views.grado_academico_nuevo, name='grado_nuevo'),
    path('gradonuevo/', views.grado_academico_nuevo2, name='grado_nuevo2'),
    path('editar/<pk>', views.ActualizaDocente.as_view(), name='docente_editar'),
    path('detalles/<id>', views.docente_detalles, name='docente_detalles'),

    path('grados/listar', views.CatGradosList.as_view(), name='grados_listar'),
    path('incidencias/listar', views.CatIncidenciasList.as_view(), name='incidencias_listar'),
    path('cuerpos/listar', views.CuerpoList.as_view(), name='cuerpos_listar'),
    path('escuelas/listar', views.EscuelasList.as_view(), name='escuelas_listar'),
    path('materias/listar', views.MateriaList.as_view(), name='materias_listar'),
    path('programas/listar', views.ProgramaList.as_view(), name='programas_listar'),
    path('unidades/listar', views.UnidadAcademicaList.as_view(), name='unidades_listar'),

    path('grados/agregar', views.CatGradosCreate.as_view(), name='grados_agregar'),
    path('incidencias/agregar', views.CatIncidenciaCreate.as_view(), name='incidencias_agregar'),
    path('cuerpos/agregar', views.CuerpoCreate.as_view(), name='cuerpos_agregar'),
    path('escuelas/agregar', views.EscuelaCreate.as_view(), name='escuelas_agregar'),
    path('materias/agregar', views.MateriaCreate.as_view(), name='materias_agregar'),
    path('programas/agregar', views.ProgramaCreate.as_view(), name='programas_agregar'),
    path('unidades/agregar', views.UnidadAcademicaCreate.as_view(), name='unidades_agregar'),

]

apps/nivel/urls.py
from django.urls import path
from apps.nivel.views import nivel_list, BanderaList, BanderaCreate, CodificacionCreate, CodificacionList,nuevo_nivel,\
    docente_nivel_list


app_name='nivel'
urlpatterns = [
    path('listar',nivel_list,name='nivel_listar'),

    path('bandera/lista', BanderaList.as_view(),name='bandera_listar'),
    path('bandera/nueva',BanderaCreate.as_view(),name='bandera_agregar'),
    path('codificacion/lista', CodificacionList.as_view(), name='codificacion_listar'),
    path('codificacion/nueva', CodificacionCreate.as_view(), name='codificacion_agregar'),
    
    path('niveles/nuevo/<id>',nuevo_nivel,name='nivel_nuevo'),
    path('historial/<id>',docente_nivel_list, name='historial_nivel')
]

apps/base/models.py
from django.db import models
from apps.docente.models import DatosPersonales, Materia
from apps.nivel.models import Oficio, Codificacion, Bandera

# Create your models here.
class Base(models.Model):
    datos_personales = models.ForeignKey(DatosPersonales, verbose_name="Docente", on_delete=models.CASCADE)
    fecha_movimiento = models.DateField()
    bandera = models.ForeignKey(Bandera, verbose_name="Bandera", on_delete=models.CASCADE)
    codificacion = models.ForeignKey(Codificacion, verbose_name="Codificacion", on_delete=models.CASCADE)
    materia = models.ManyToManyField(Materia)
    funcion = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.datos_personales} {self.bandera}"

apps/base/forms.py
from django import forms
from django.shortcuts import redirect, render
from tempus_dominus.widgets import DatePicker, TimePicker, DateTimePicker
from apps.base import models


class BaseForm(forms.ModelForm):
    class Meta:
        model = models.Base
        fields = '__all__'
        exclude = ('datos_personales', 'oficio',)

        widgets = {
            'fecha_movimiento': DatePicker(),
        }

apps/base/views.py
from django.shortcuts import render, redirect
from django.db.models import Max
from apps.docente.models import DatosPersonales
from apps.base.models import Base
from apps.base.forms import  BaseForm
from apps.nivel.forms import OficioForm

# Create your views here.

def base_list(request):

    ## Por ahora solo muestra los que ya tienen un nivel, hay que ver como hacer un
    # outer join para mostrar tambien los que no tiene nivel

    ultimas_bases_ids = DatosPersonales.objects.annotate(
        ultima_base_id=Max('base__id')).values_list('ultima_base_id', flat=True)
    #
    ultimas_bases = Base.objects.filter(id__in=ultimas_bases_ids).order_by('datos_personales__nombres')

    #lista = zip(docentes, niveles)
    context = {
        'bases': ultimas_bases,
    }
    return render(request, 'base_docente/lista_bases.html', context)


def nueva_base(request, id):
    docente = DatosPersonales.objects.get(pk=id)
    if request.method == 'POST':
        form_base = BaseForm(request.POST)
        form_oficio = OficioForm(request.POST)
        if form_base.is_valid() and form_oficio.is_valid():
            base = form_base.save(commit=False)
            oficio = form_oficio.save()

            base.datos_personales = docente
            base.oficio = oficio

            base.save()
            return redirect('base:base_listar')
        return redirect('base:base_listar')
    else:
        form_base = BaseForm()
        form_oficio = OficioForm()
    return render(request, 'base_docente/base_form.html',
                  {
                      'form_base': form_base,
                      'form_oficio': form_oficio,
                      'docente': docente.nombres,
                  })


def docente_base_list(request, id):
    docente = DatosPersonales.objects.get(pk=id)
    bases = docente.base_set.all().order_by('fecha_movimiento')

    # lista = zip(docentes, niveles)
    context = {
        'docente': docente,
        'bases': bases,
    }
    return render(request, 'base_docente/lista_bases_docente.html', context)

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>
  {% block title %}
      SAPDUAZ - Dashboard
  {% endblock title %}
   </title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.css">

    {# Include Bootstrap 4 and jQuery #}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>


  
  {% block extrahead %}
      
  {% endblock extrahead %}

</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    
    {% block sidebar %}
        {% include 'base/sidebar.html' %}
    {% endblock sidebar %}
        
    
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        
        {% block topbar %}
            {% include 'base/topbar.html' %}
        {% endblock topbar %}
            
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid"> 

          <!-- Page Heading -->
            {% block heading %}
                {% include 'base/heading.html' %}
            {% endblock heading %}
          

          
            {% block content %}
              
            {% endblock content %}
              

        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->

      
      {% block footer %}
          {% include 'base/footer.html' %}
      {% endblock footer %}
          
      
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Cerrar sesión</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">¿Deseas cerrar tu sesión?.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{% url 'logout' %}">Logout</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>


  <script src="{% static 'js/scripts.js' %}"></script>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

  {% block extrascripts %}
      
  {% endblock extrascripts %}
      

</body>

</html>

templates/base/confirm_delete_modal.html
<!--Delete button will redirect to the href of the element with 'id = caller-id' property in this modal-->
<div class="modal fade" id="confirmDeleteModal" tabindex="-1" caller-id="" role="dialog" aria-labelledby="confirmDeleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body confirm-delete">
        ¿Deseas cambiar es status del docente seleccionado?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
        <button type="button" class="btn btn-primary" data-dismiss="modal" id="confirmDeleteButtonModal">Aceptar</button>
      </div>
    </div>
  </div>
</div>

templates/base/footer.html
{% block footer %}

<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
        <span>Copyright &copy; Universidad Autónoma de Zacatecas 2019</span>
        </div>
    </div>
</footer>
    
{% endblock footer %}
    

templates/base/heading.html
{% block heading %}
    
<div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
        <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>
</div>

{% endblock heading %}

templates/base/sidebar.html
{% block sidebar %}
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

        <!-- Sidebar - Brand -->
        <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'index' %}">
          <!--<div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-address-card"></i>
          </div>-->
          <div class="sidebar-brand-text mx-3">SAPDUAZ <!--sup>2</sup--></div>
        </a>
  
        <!-- Divider -->
        <hr class="sidebar-divider my-0">
  
        <!-- Nav Item - Dashboard -->
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'index' %}">
            <i class="fas fa-fw fa-home"></i>
            <span>Inicio</span></a>
        </li>
  
        <!-- Divider -->
        <hr class="sidebar-divider">
  
        <!-- Heading -->
        <div class="sidebar-heading">
          Acciones
        </div>
  
        <!-- Nav Item - Docentes Collapse Menu -->
        <li class="nav-item">
          <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseDocente" aria-expanded="true" aria-controls="collapseDocente">
            <i class="fas fa-fw fa-user-tie"></i>
            <span>Docentes</span>
          </a>
          <div id="collapseDocente" class="collapse" aria-labelledby="headingDocentes" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
              <h6 class="collapse-header">Acciones:</h6>
              <a class="collapse-item" href="{% url 'docente:docente_listar' %}">Lista Docentes</a>
              <a class="collapse-item" href="{% url 'docente:docente_nuevo' %}">Nuevo Docente</a>
            </div>
          </div>
        </li>
  
        <!-- Nav Item - Nivel Collapse Menu -->
        <li class="nav-item">
          <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseNivel" aria-expanded="true" aria-controls="collapseNivel">
            <i class="fas fa-fw fa-layer-group"></i>
            <span>Nivel</span>
          </a>
          <div id="collapseNivel" class="collapse" aria-labelledby="headingNivel" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
              <h6 class="collapse-header">Acciones</h6>
              <a class="collapse-item" href="{% url 'nivel:nivel_listar' %}">Lista de Niveles</a>
            </div>
          </div>
        </li>

        <!-- Nav Item - Base Collapse Menu -->
        <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseBase" aria-expanded="true" aria-controls="collapseBase">
              <i class="fas fa-fw fa-suitcase"></i>
              <span>Base</span>
            </a>
            <div id="collapseBase" class="collapse" aria-labelledby="headingBase" data-parent="#accordionSidebar">
              <div class="bg-white py-2 collapse-inner rounded">
                  <h6 class="collapse-header">Acciones</h6>
                  <a class="collapse-item" href="{% url 'base:base_listar' %}">Lista de Bases</a>
              </div>
            </div>
          </li>

        <li class="nav-item">
            <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseInterrupcion" aria-expanded="true" aria-controls="collapseInterrupcion">
              <i class="fas fa-fw fa-user-clock"></i>
              <span>Interrupciones</span>
            </a>
            <div id="collapseInterrupcion" class="collapse" aria-labelledby="headingInterrupcion" data-parent="#accordionSidebar">
              <div class="bg-white py-2 collapse-inner rounded">
                  <h6 class="collapse-header">Acciones</h6>
                  <a class="collapse-item" href="#">Lista</a>
              </div>
            </div>
        </li>

        <!-- Catalogos-->
        <li class="nav-item">
          <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseCatalogo" aria-expanded="true" aria-controls="collapseCatalogo">
            <i class="fas fa-fw fa-book"></i>
            <span>Catálogos</span>
          </a>
          <div id="collapseCatalogo" class="collapse" aria-labelledby="headingCatalogo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
              <h6 class="collapse-header">Catalogos</h6>
                <a class="collapse-item" href="{% url 'docente:incidencias_listar' %}">Categorias Incidencias</a>
{#                <a class="collapse-item" href="{% url 'docente:grados_listar' %}">Categorias Grados</a>#}
                <a class="collapse-item" href="{% url 'docente:escuelas_listar' %}">Escuelas</a>
                <a class="collapse-item" href="{% url 'docente:unidades_listar' %}">Unidades Academicas</a>
                <a class="collapse-item" href="{% url 'docente:programas_listar' %}">Programas</a>
                <a class="collapse-item" href="{% url 'docente:materias_listar' %}">Materias</a>
                <a class="collapse-item" href="{% url 'docente:cuerpos_listar' %}">Cuerpos Academicos</a>
                <a class="collapse-item" href="{% url 'nivel:bandera_listar' %}">Banderas</a>
                <a class="collapse-item" href="{% url 'nivel:codificacion_listar' %}">Codificaciones</a>
                <a class="collapse-item" href="#">Estados</a>
                <a class="collapse-item" href="#">Municipios</a>
            </div>
          </div>
        </li>
  
        <!-- Divider -->
        <hr class="sidebar-divider d-none d-md-block">
  
        <!-- Sidebar Toggler (Sidebar) -->
        <div class="text-center d-none d-md-inline">
          <button class="rounded-circle border-0" id="sidebarToggle"></button>
        </div>
  
      </ul>  
{% endblock sidebar %}

templates/base/topbar.html
{% block topbar %}
    
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

        <!-- Sidebar Toggle (Topbar) -->
        <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
          <i class="fa fa-bars"></i>
        </button>

        <!-- Topbar Search 
        <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
          <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small" placeholder="Buscar..." aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
              <button class="btn btn-primary" type="button">
                <i class="fas fa-search fa-sm"></i>
              </button>
            </div>
          </div>
        </form>-->

        <!-- Topbar Navbar -->
        <ul class="navbar-nav ml-auto">

          <!-- Nav Item - Search Dropdown (Visible Only XS) -->
          <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-search fa-fw"></i>
            </a>
            <!-- Dropdown - Messages
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
              <form class="form-inline mr-auto w-100 navbar-search">
                <div class="input-group">
                  <input type="text" class="form-control bg-light border-0 small" placeholder="Buscar..." aria-label="Search" aria-describedby="basic-addon2">
                  <div class="input-group-append">
                    <button class="btn btn-primary" type="button">
                      <i class="fas fa-search fa-sm"></i>
                    </button>
                  </div>
                </div>
              </form>
            </div>
          </li> -->

          

          <div class="topbar-divider d-none d-sm-block"></div> -->

          <!-- Nav Item - User Information -->
          <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{user}}</span>
              <!--<img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">-->
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
              <a class="dropdown-item" href="#">
                <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                Perfil
              </a>
              <a class="dropdown-item" href="#">
                <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                Configuración
              </a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                Cerrar sesión
              </a>
            </div>
          </li>

        </ul>

      </nav>



{% endblock topbar %}