SAPDUAZ2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apps.docente.views import Index
from django.contrib.auth.views import LogoutView

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('logout', LogoutView.as_view(), name='logout'),
                  path('docente/', include('apps.docente.urls', namespace='docente')),
                  path('nivel/', include('apps.nivel.urls', namespace='nivel')),
                  path('base/', include('apps.base.urls', namespace='base')),
                  path('index', Index.as_view(), name='index')
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/nivel/urls.py
from django.urls import path
from apps.nivel.views import nivel_list, BanderaList, BanderaCreate, CodificacionCreate, CodificacionList,nuevo_nivel,\
    docente_nivel_list


app_name='nivel'
urlpatterns = [
    path('listar',nivel_list,name='nivel_listar'),

    path('bandera/lista', BanderaList.as_view(),name='bandera_listar'),
    path('bandera/nueva',BanderaCreate.as_view(),name='bandera_agregar'),
    path('codificacion/lista', CodificacionList.as_view(), name='codificacion_listar'),
    path('codificacion/nueva', CodificacionCreate.as_view(), name='codificacion_agregar'),
    
    path('niveles/nuevo/<id>',nuevo_nivel,name='nivel_nuevo'),
    path('historial/<id>',docente_nivel_list, name='historial_nivel')
]

apps/nivel/models.py
import os
from uuid import uuid4
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from apps.docente.choices import *
from apps.docente.models import DatosPersonales


# Create your models here.
def path_and_rename(instance, filename):
    ext = filename.split('.')[-1]
    # get filename
    if isinstance (instance,Jubilado):
        upload_to = 'jubilados'
        filename = '{}_{}.{}'.format(instance.docente, instance.fecha, ext)
    elif isinstance (instance,Pensionado):
        upload_to = 'pensionados'
        filename = '{}_{}.{}'.format(instance.docente, instance.fecha, ext)
    elif isinstance (instance,Oficio):
        upload_to = 'oficios'
        filename = '{}_{}.{}'.format(instance.numero, instance.fecha_oficio, ext)
    else:
        upload_to = 'documentos'        

    # return the whole path to the file
    return os.path.join(upload_to, filename)

class Codificacion(models.Model):
    cod = models.IntegerField(validators=[
            MaxValueValidator(999),
            MinValueValidator(1)
        ])
    tipo_nivel = models.CharField(max_length=10,choices=NIVEL)
    grupo_laboral = models.CharField(max_length=100,choices=GPO_LABORAL)
    categoria = models.CharField(max_length=50,choices=CATEGORIA_COD)

    def __str__(self):
        return f"[{self.cod}] {self.categoria} {self.grupo_laboral} {self.tipo_nivel}"

LONGITUD_MAXIMA = 'Excediste la longitud'
class Bandera(models.Model):
    clave = models.CharField(max_length=10, verbose_name="Clave")
    nombre = models.CharField(max_length=120)
    id_categoria = models.CharField(max_length=5, choices=CATEGORIAS_BANDERA)

    def __str__(self):
        return self.nombre
    
class Oficio(models.Model):
    numero = models.IntegerField()
    emisor = models.CharField(max_length=20, choices=OFICIO)
    fecha_oficio = models.DateField()
    imagen_oficios = models.ImageField("Oficio", upload_to=path_and_rename, null=True, blank=True)
    
    def __str__(self):
        return f"Oficio {self.numero} Fecha: {self.fecha_oficio}"

    
class Pensionado(models.Model):
    docente = models.ForeignKey(DatosPersonales, verbose_name="Docente", on_delete=models.CASCADE)
    #bandera = models.ForeignKey(Bandera, verbose_name="Bandera", on_delete=models.CASCADE)
    beneficiarios = models.CharField(max_length=10)
    fecha = models.DateField()
    oficio = models.ForeignKey(Oficio, verbose_name="Oficio", on_delete=models.CASCADE)
    observaciones = models.TextField(blank=True, null=True)
    
class Jubilado(models.Model):
    docente = models.ForeignKey(DatosPersonales, verbose_name="Docente", on_delete=models.CASCADE)
    bandera = models.ForeignKey(Bandera, verbose_name="Bandera", on_delete=models.CASCADE)
    fecha = models.DateField()
    oficio = models.ForeignKey(Oficio, verbose_name="Oficio", on_delete=models.CASCADE)
    observaciones = models.TextField(blank=True, null=True)

class Nivel(models.Model):
    datos_personales = models.ForeignKey(DatosPersonales, verbose_name="Docente", on_delete=models.CASCADE)
    oficio = models.ForeignKey(Oficio, verbose_name="Oficio", on_delete=models.CASCADE)
    fecha_movimiento = models.DateField()
    via = models.CharField(max_length=10, choices=VIA, default='REQUISITOS')
    bandera = models.ForeignKey(Bandera, verbose_name="Bandera", on_delete=models.CASCADE)
    cod_nivel = models.ForeignKey(Codificacion, verbose_name="Codificacion", on_delete=models.CASCADE)
    observaciones = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.datos_personales} Vía:{self.via} Bandera: {self.bandera}"

apps/nivel/forms.py
from django import forms
from django.shortcuts import redirect, render
from tempus_dominus.widgets import DatePicker, TimePicker, DateTimePicker

from apps.nivel import models
from apps.nivel.models import LONGITUD_MAXIMA


class BanderaForm(forms.ModelForm):
    class Meta:
        model = models.Bandera
        fields = '__all__'

        error_messages = {
            'nombre': {'max_length': LONGITUD_MAXIMA, 'required': 'Se requiere'}
        }


class CodificacionForm(forms.ModelForm):
    class Meta:
        model = models.Codificacion
        fields = '__all__'

class OficioForm(forms.ModelForm):
    class Meta:
        model = models.Oficio
        fields = '__all__'
        widgets={
            'fecha_oficio':DatePicker(),
        }
        
class NivelForm(forms.ModelForm):
    class Meta:
        model = models.Nivel
        fields = '__all__'
        exclude = ('datos_personales','oficio',)
        
        widgets={
            'fecha_movimiento':DatePicker(),
        }

apps/nivel/views.py
from django.db.models import Max
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, TemplateView, CreateView

from apps.docente.models import DatosPersonales
from apps.nivel.models import Nivel, Bandera, Codificacion, Oficio
from apps.nivel.forms import BanderaForm,CodificacionForm,OficioForm,NivelForm

# Create your views here.
class ListaBase(ListView):
    model = Bandera
    # permission_required = 'dinosaurios.view_dinosaurio'
    
def nivel_list(request):
    # docente = DatosPersonales.objects.all()
    # niveles = Nivel.objects.all()
    #
    # docente_niveles = docente.


    ## Por ahora solo muestra los que ya tienen un nivel, hay que ver como hacer un
    # outer join para mostrar tambien los que no tiene nivel

    ultimos_niveles_ids = DatosPersonales.objects.annotate(
        ultimo_nivel_id=Max('nivel__id')).values_list('ultimo_nivel_id', flat=True)
    ultimos_niveles = Nivel.objects.filter(id__in=ultimos_niveles_ids).order_by('datos_personales__nombres')

    #lista = zip(docentes, niveles)
    context = {
        'niveles': ultimos_niveles,
    }
    return render(request, 'nivel/lista_niveles.html', context)



class BanderaList(ListView):
    model = Bandera
    template_name = 'catalogos/banderas_list.html'
    paginate_by = 10


class BanderaCreate(CreateView):
    model = Bandera
    form_class = BanderaForm
    template_name = 'catalogos/bandera_form.html'
    success_url = reverse_lazy('nivel:banderas_listar')


class CodificacionList(ListView):
    model = Codificacion
    template_name = 'catalogos/codificaciones_list.html'
    paginate_by = 10


class CodificacionCreate(CreateView):
    model = Codificacion
    form_class = CodificacionForm
    template_name = 'catalogos/codificaciones_form.html'
    success_url = reverse_lazy('nivel:codificiaciones_listar')
    
    
def nuevo_nivel(request, id):
    docente = DatosPersonales.objects.get(pk=id)
    if request.method == 'POST':
        form_nivel = NivelForm(request.POST)
        form_oficio = OficioForm(request.POST)
        if form_nivel.is_valid() and form_oficio.is_valid():
            nivel = form_nivel.save(commit=False)
            oficio = form_oficio.save()
            
            nivel.datos_personales = docente
            nivel.oficio = oficio
            
            nivel.save()
            return redirect('nivel:nivel_listar')
        return redirect('nivel:nivel_listar')
    else:
        form_nivel = NivelForm()
        form_oficio = OficioForm()
    return render(request, 'nivel/nivel_form.html',
                  {
                      'form_nivel': form_nivel,
                      'form_oficio':form_oficio,
                      'docente': docente.nombres,
                  })

def docente_nivel_list(request,id):
    docente = DatosPersonales.objects.get(pk=id)
    niveles = docente.nivel_set.all().order_by('fecha_movimiento')

    #lista = zip(docentes, niveles)
    context = {
        'docente':docente,
        'niveles': niveles,
    }
    return render(request, 'nivel/lista_niveles_docente.html', context)

templates/nivel/lista_niveles.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
   Lista Docentes 
{% endblock title %}
    

{% block extrahead %}
<link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock extrahead %}
    

        <!-- Page Heading -->
        
        {% block heading %}
        <h1 class="h3 mb-2 text-gray-800">Lista de Niveles</h1>
        <p class="mb-4">Descripcion</p>

        {% endblock heading %}
            

        {% block content %}
    
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary"></h6>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Nivel Actual</th>
                    <th>Fecha Nivel</th>
                    <th>Bandera</th>
                    <th>Acciones</th>
                  </tr>
                </thead>
                <tfoot>
                  <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Nivel Actual</th>
                    <th>Fecha Nivel</th>
                    <th>Bandera</th>
                    <th>Acciones</th>
                  </tr>
                </tfoot>
                <tbody>
        
                  {% for nivel in niveles %}
                        <tr>
                            <td>{{nivel.datos_personales.pk}}</td>
                            <td>{{nivel.datos_personales.nombres}} {{nivel.datos_personales.ap_paterno}} {{nivel.datos_personales.ap_materno}}</td>
                            <td>{{nivel.cod_nivel}}</td>
                            <td>{{ nivel.fecha_movimiento }}</td>
                            <td>{{ nivel.bandera }}</td>
                            <td>
                                <div class="dropdown mb-4">
                                    <button class="btn btn-danger dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Acciones
                                    </button>
                                    <div class="dropdown-menu animated--fade-in" aria-labelledby="dropdownMenuButton">
                                        <a class="dropdown-item" href="{% url 'nivel:historial_nivel' nivel.datos_personales.pk %}"><i class="fas fa-fw fa-sync"></i>Historial de niveles</a>
                                        <a class="dropdown-item" href="{% url 'nivel:nivel_nuevo' nivel.datos_personales.pk %}"><i class="fas fa-fw fa-history"></i>Actualizar nivel</a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
        {% endblock content %}

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
  <i class="fas fa-angle-up"></i>
</a>


{% block extrascripts %}
<!-- Page level plugins -->
<script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

<!-- Page level custom scripts -->
<script src="{% static 'js/demo/datatables-demo.js' %}"></script>
{% endblock extrascripts %}
    

templates/nivel/lista_niveles_docente.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
   Historial Niveles
{% endblock title %}
    

{% block extrahead %}
<link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock extrahead %}
    

        <!-- Page Heading -->
        
        {% block heading %}
        <h1 class="h3 mb-2 text-gray-800">Historial de niveles de {{ docente }}</h1>
        <p class="mb-4">Descripcion</p>

        {% endblock heading %}
            

        {% block content %}
    
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary"></h6>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                  <tr>
                    <th>Bandera</th>
                    <th>Codificacion</th>
                    <th>Fecha Movimiento</th>
                    <th>Via</th>
                    <th>Oficio</th>
                    <th>Observaciones</th>
                      <th>Acciones</th>
                  </tr>
                </thead>
                <tfoot>
                  <tr>
                    <th>Bandera</th>
                    <th>Codificacion</th>
                    <th>Fecha Movimiento</th>
                    <th>Via</th>
                    <th>Oficio</th>
                    <th>Observaciones</th>
                      <th>Acciones</th>
                  </tr>
                </tfoot>
                <tbody>
        
                  {% for nivel in niveles %}
                          <tr>
                              <td>{{nivel.bandera}}</td>
                              <td>{{nivel.cod_nivel}}</td>
                              <td>{{nivel.fecha_movimiento}}</td>
                              <td>{{nivel.via}}</td>
                              <td><a href="{{ MEDIA_URL }}{{nivel.oficio.imagen_oficios}}">{{nivel.oficio.imagen_oficios}}</a></td>
                              <td>{{nivel.observaciones}}</td>
                              <td>
                                <div class="dropdown mb-4">
                                    <button class="btn btn-danger dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Acciones
                                    </button>
                                    <div class="dropdown-menu animated--fade-in" aria-labelledby="dropdownMenuButton">
                                        <a class="dropdown-item" href="#"><i class="fas fa-fw fa-info-circle"></i>Editar</a>
                                        <a class="dropdown-item" href="#"><i class="fas fa-fw fa-pen-square"></i>Eliminar</a>
                                    </div>
                                </div>
                            </td>
                          </tr>
                      {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
        {% endblock content %}

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
  <i class="fas fa-angle-up"></i>
</a>


{% block extrascripts %}
<!-- Page level plugins -->
<script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

<!-- Page level custom scripts -->
<script src="{% static 'js/demo/datatables-demo.js' %}"></script>
{% endblock extrascripts %}
    

templates/nivel/nivel_form.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}

{% block extrahead %}
    {{ form_nivel.media }}
{% endblock %}

{% block content %}

    <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Nuevo Nivel para docente {{docente}}</h6>
        </div>
        <div class="card-body">
            <form method="post" class="form" enctype="multipart/form-data">
                {% csrf_token %}
                <h3>Informacion del Nivel</h3>
                {{ form_nivel.as_p }}
                <h3>Información del Oficio</h3>
                {{ form_oficio.as_p }}
                <button type="submit" class="btn btn-primary">Guardar</button>
            </form>
        </div>
    </div>


{% endblock %}