SAPDUAZ2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apps.docente.views import Index
from django.contrib.auth.views import LogoutView

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('logout', LogoutView.as_view(), name='logout'),
                  path('docente/', include('apps.docente.urls', namespace='docente')),
                  path('nivel/', include('apps.nivel.urls', namespace='nivel')),
                  path('base/', include('apps.base.urls', namespace='base')),
                  path('index', Index.as_view(), name='index')
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/docente/urls.py
from django.urls import path
from apps.docente import views

app_name = 'docente'
urlpatterns = [
    path('listar', views.ListaDocentes.as_view(), name='docente_listar'),
    path('activar/<id>', views.docente_activate, name='docente_activar'),
    path('nuevo/', views.NuevoDocente.as_view(), name='docente_nuevo'),
    path('gradonuevo/<id>', views.grado_academico_nuevo, name='grado_nuevo'),
    path('gradonuevo/', views.grado_academico_nuevo2, name='grado_nuevo2'),
    path('editar/<pk>', views.ActualizaDocente.as_view(), name='docente_editar'),
    path('detalles/<id>', views.docente_detalles, name='docente_detalles'),

    path('grados/listar', views.CatGradosList.as_view(), name='grados_listar'),
    path('incidencias/listar', views.CatIncidenciasList.as_view(), name='incidencias_listar'),
    path('cuerpos/listar', views.CuerpoList.as_view(), name='cuerpos_listar'),
    path('escuelas/listar', views.EscuelasList.as_view(), name='escuelas_listar'),
    path('materias/listar', views.MateriaList.as_view(), name='materias_listar'),
    path('programas/listar', views.ProgramaList.as_view(), name='programas_listar'),
    path('unidades/listar', views.UnidadAcademicaList.as_view(), name='unidades_listar'),

    path('grados/agregar', views.CatGradosCreate.as_view(), name='grados_agregar'),
    path('incidencias/agregar', views.CatIncidenciaCreate.as_view(), name='incidencias_agregar'),
    path('cuerpos/agregar', views.CuerpoCreate.as_view(), name='cuerpos_agregar'),
    path('escuelas/agregar', views.EscuelaCreate.as_view(), name='escuelas_agregar'),
    path('materias/agregar', views.MateriaCreate.as_view(), name='materias_agregar'),
    path('programas/agregar', views.ProgramaCreate.as_view(), name='programas_agregar'),
    path('unidades/agregar', views.UnidadAcademicaCreate.as_view(), name='unidades_agregar'),

]

apps/nivel/urls.py
from django.urls import path
from apps.nivel.views import nivel_list, BanderaList, BanderaCreate, CodificacionCreate, CodificacionList,nuevo_nivel,\
    docente_nivel_list


app_name='nivel'
urlpatterns = [
    path('listar',nivel_list,name='nivel_listar'),

    path('bandera/lista', BanderaList.as_view(),name='bandera_listar'),
    path('bandera/nueva',BanderaCreate.as_view(),name='bandera_agregar'),
    path('codificacion/lista', CodificacionList.as_view(), name='codificacion_listar'),
    path('codificacion/nueva', CodificacionCreate.as_view(), name='codificacion_agregar'),
    
    path('niveles/nuevo/<id>',nuevo_nivel,name='nivel_nuevo'),
    path('historial/<id>',docente_nivel_list, name='historial_nivel')
]

templates/catalogos/banderas_list.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
   Lista de Grados
{% endblock title %}
    

{% block extrahead %}
<link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock extrahead %}
    

        <!-- Page Heading -->
        
        {% block heading %}

        <div class="d-sm-flex align-items-center justify-content-between mb-4">
                <h1 class="h3 mb-2 text-gray-800">Catálogo de Banderas</h1>
                <a href="{% url 'nivel:bandera_agregar' %}" class="d-none d-sm-inline-block btn btn-sm btn-success shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Nueva Bandera</a>
        </div>
        {% endblock heading %}
            

        {% block content %}
    
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary"></h6>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                  <tr>
                    <th>Clave</th>
                    <th>Nombre</th>
                    <th>Categoria</th>
                  </tr>
                </thead>
                <tfoot>
                  <tr>
                      <th>Clave</th>
                      <th>Nombre</th>
                      <th>Categoria</th>
                  </tr>
                </tfoot>
                <tbody>
        
                    {% for a in object_list %}
                        <tr>
                            <td>{{a.clave}}</td>
                            <td>{{a.nombre}}</td>
                            <td>{{a.id_categoria}}</td>
                            <td>
                                <div class="dropdown mb-4">
                                    <button class="btn btn-danger dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Acciones
                                    </button>
                                    <div class="dropdown-menu animated--fade-in" aria-labelledby="dropdownMenuButton">
                                        <a class="dropdown-item" href="#"><i class="fas fa-fw fa-info-circle"></i>Editar</a>
                                        <a class="dropdown-item" href="#"><i class="fas fa-fw fa-pen-square"></i>Eliminar</a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>

{% include 'base/confirm_delete_modal.html' %}
{% endblock content %}

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
  <i class="fas fa-angle-up"></i>
</a>



{% block extrascripts %}
<!-- Page level plugins -->
<script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

<!-- Page level custom scripts -->
<script src="{% static 'js/demo/datatables-demo.js' %}"></script>

{% endblock extrascripts %}

templates/catalogos/cat_grados_form.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}
{% block content %}

    <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Nueva Categoria de Grados</h6>
        </div>
        <div class="card-body">
            <form  method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Guardar</button>
            </form>
        </div>
    </div>


{% endblock %}

templates/catalogos/cat_grados_list.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
   Lista de Grados
{% endblock title %}
    

{% block extrahead %}
<link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock extrahead %}
    

        <!-- Page Heading -->
        
        {% block heading %}

        <div class="d-sm-flex align-items-center justify-content-between mb-4">
                <h1 class="h3 mb-2 text-gray-800">Catalogo de Grados Académicos</h1>
                <a href="{% url 'docente:grados_agregar' %}" class="d-none d-sm-inline-block btn btn-sm btn-success shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Nuevo Grado</a>
        </div>
        {% endblock heading %}
            

        {% block content %}
    
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary"></h6>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Descripcion</th>
                    <th>Acciones</th>
                  </tr>
                </thead>
                <tfoot>
                  <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Descripcion</th>
                    <th>Acciones</th>
                  </tr>
                </tfoot>
                <tbody>
        
                    {% for a in object_list %}
                        <tr>
                            <td>{{a.pk}}</td>
                            <td>{{a.nombre}}</td>
                            <td>{{a.desc}}</td>
                            <td>
                                <div class="dropdown mb-4">
                                    <button class="btn btn-danger dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Acciones
                                    </button>
                                    <div class="dropdown-menu animated--fade-in" aria-labelledby="dropdownMenuButton">
                                        <a class="dropdown-item" href="#"><i class="fas fa-fw fa-info-circle"></i>Editar</a>
                                        <a class="dropdown-item" href="#"><i class="fas fa-fw fa-pen-square"></i>Eliminar</a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>

{% include 'base/confirm_delete_modal.html' %}
{% endblock content %}

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
  <i class="fas fa-angle-up"></i>
</a>



{% block extrascripts %}
<!-- Page level plugins -->
<script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

<!-- Page level custom scripts -->
<script src="{% static 'js/demo/datatables-demo.js' %}"></script>

{% endblock extrascripts %}

templates/catalogos/cat_incidencias_form.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}
{% block content %}

    <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Nueva Categoria de incidencias</h6>
        </div>
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Guardar</button>
            </form>
        </div>
    </div>


{% endblock %}

templates/catalogos/cat_incidencias_list.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
   Lista Incidencias
{% endblock title %}
    

{% block extrahead %}
<link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock extrahead %}

        <!-- Page Heading -->
        
        {% block heading %}
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
                <h1 class="h3 mb-2 text-gray-800">Catalogo de Incidenciasc</h1>
                <a href="{% url 'docente:incidencias_agregar' %}" class="d-none d-sm-inline-block btn btn-sm btn-success shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Nuevo Tipo Incidencia</a>
        </div>
        {% endblock heading %}

        {% block content %}
    
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary"></h6>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>Permiso</th>
                    <th>Clausula</th>
                    <th>Acciones</th>
                  </tr>
                </thead>
                <tfoot>
                  <tr>
                    <th>ID</th>
                    <th>Permiso</th>
                    <th>Clausula</th>
                    <th>Acciones</th>
                  </tr>
                </tfoot>
                <tbody>
        
                    {% for a in object_list %}
                        <tr>
                            <td>{{a.pk}}</td>
                            <td>{{a.permiso}}</td>
                            <td>{{a.clausula}}</td>
                            <td>
                                <div class="dropdown mb-4">
                                    <button class="btn btn-danger dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Acciones
                                    </button>
                                    <div class="dropdown-menu animated--fade-in" aria-labelledby="dropdownMenuButton">
                                        <a class="dropdown-item" href="#"><i class="fas fa-fw fa-info-circle"></i>Editar</a>
                                        <a class="dropdown-item" href="#"><i class="fas fa-fw fa-pen-square"></i>Eliminar</a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>

{% include 'base/confirm_delete_modal.html' %}
{% endblock content %}

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
  <i class="fas fa-angle-up"></i>
</a>



{% block extrascripts %}
<!-- Page level plugins -->
<script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

<!-- Page level custom scripts -->
<script src="{% static 'js/demo/datatables-demo.js' %}"></script>

{% endblock extrascripts %}

templates/catalogos/codificaciones_form.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}
{% block content %}

    <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Nueva Codificacion</h6>
        </div>
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Guardar</button>
            </form>
        </div>
    </div>


{% endblock %}

templates/catalogos/codificaciones_list.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
   Lista Incidencias
{% endblock title %}
    

{% block extrahead %}
<link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock extrahead %}

        <!-- Page Heading -->
        
        {% block heading %}
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
                <h1 class="h3 mb-2 text-gray-800">Catálogo Codificaciones</h1>
                <a href="{% url 'nivel:codificacion_agregar' %}" class="d-none d-sm-inline-block btn btn-sm btn-success shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i>Nueva Codificacion</a>
        </div>
        {% endblock heading %}

        {% block content %}
    
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary"></h6>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                  <tr>
                    <th>Codigo</th>
                    <th>Tipo de Nivel</th>
                    <th>Grupo Laboral</th>
                    <th>Categoria</th>
                    <th>Acciones</th>
                  </tr>
                </thead>
                <tfoot>
                  <tr>
                    <th>Codigo</th>
                    <th>Tipo de Nivel</th>
                    <th>Grupo Laboral</th>
                    <th>Categoria</th>
                    <th>Acciones</th>
                  </tr>
                </tfoot>
                <tbody>
        
                    {% for a in object_list %}
                        <tr>
                            <td>{{a.cod}}</td>
                            <td>{{a.tipo_nivel}}</td>
                            <td>{{a.grupo_laboral}}</td>
                            <td>{{a.categoria}}</td>
                            <td>
                                <div class="dropdown mb-4">
                                    <button class="btn btn-danger dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Acciones
                                    </button>
                                    <div class="dropdown-menu animated--fade-in" aria-labelledby="dropdownMenuButton">
                                        <a class="dropdown-item" href="#"><i class="fas fa-fw fa-info-circle"></i>Editar</a>
                                        <a class="dropdown-item" href="#"><i class="fas fa-fw fa-pen-square"></i>Eliminar</a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>

{% include 'base/confirm_delete_modal.html' %}
{% endblock content %}

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
  <i class="fas fa-angle-up"></i>
</a>



{% block extrascripts %}
<!-- Page level plugins -->
<script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

<!-- Page level custom scripts -->
<script src="{% static 'js/demo/datatables-demo.js' %}"></script>

{% endblock extrascripts %}

templates/catalogos/cuerpo_form.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}
{% block content %}

    <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Nueva Cuerpo Académico</h6>
        </div>
        <div class="card-body">
            <form  method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Guardar</button>
            </form>
        </div>
    </div>


{% endblock %}

templates/catalogos/cuerpos_list.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
   Lista cuerpos
{% endblock title %}
    

{% block extrahead %}
<link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock extrahead %}
    

        <!-- Page Heading -->
        
        {% block heading %}
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
                <h1 class="h3 mb-2 text-gray-800">Catalogo de Cuerpos Académicos</h1>
                <a href="{% url 'docente:cuerpos_agregar' %}" class="d-none d-sm-inline-block btn btn-sm btn-success shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Nuevo Cuerpo Académico</a>
        </div>

        {% endblock heading %}
            

        {% block content %}
    
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary"></h6>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>Numero de Registro</th>
                    <th>Nombre</th>
                    <th>Unidad Academica</th>
                    <th>Fecha Inicio</th>
                    <th>Fecha Fin</th>
                    <th>Acciones</th>
                  </tr>
                </thead>
                <tfoot>
                  <tr>
                    <th>ID</th>
                    <th>Numero de Registro</th>
                    <th>Nombre</th>
                    <th>Unidad Academica</th>
                    <th>Fecha Inicio</th>
                    <th>Fecha Fin</th>
                    <th>Acciones</th>
                  </tr>
                </tfoot>
                <tbody>
        
                    {% for a in object_list %}
                        <tr>
                            <th>{{ a.pk }}</th>
                            <td>{{a.no_registro}}</td>
                            <td>{{a.nombre}}</td>
                            <td>{{a.unidad_academica}}</td>
                            <td>{{a.fecha_inicio}}</td>
                            <td>{{ a.fecha_fin }}</td>

                            <td>
                                <div class="dropdown mb-4">
                                    <button class="btn btn-danger dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Acciones
                                    </button>
                                    <div class="dropdown-menu animated--fade-in" aria-labelledby="dropdownMenuButton">
                                        <a class="dropdown-item" href="#"><i class="fas fa-fw fa-info-circle"></i>Editar</a>
                                        <a class="dropdown-item" href="#"><i class="fas fa-fw fa-pen-square"></i>Eliminar</a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>

{% include 'base/confirm_delete_modal.html' %}
{% endblock content %}

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
  <i class="fas fa-angle-up"></i>
</a>



{% block extrascripts %}
<!-- Page level plugins -->
<script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

<!-- Page level custom scripts -->
<script src="{% static 'js/demo/datatables-demo.js' %}"></script>

{% endblock extrascripts %}

templates/catalogos/escuelas_list.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
   Lista escuelas
{% endblock title %}
    

{% block extrahead %}
<link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock extrahead %}
    

        <!-- Page Heading -->
        
        {% block heading %}
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
                <h1 class="h3 mb-2 text-gray-800">Catalogo de Escuelas</h1>
                <a href="{% url 'docente:escuelas_agregar' %}" class="d-none d-sm-inline-block btn btn-sm btn-success shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Nueva Escuela</a>
        </div>
        {% endblock heading %}
            

        {% block content %}
    
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary"></h6>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>Clave</th>
                    <th>Nombre</th>
                    <th>Acciones</th>
                  </tr>
                </thead>
                <tfoot>
                  <tr>
                    <th>ID</th>
                    <th>Clave</th>
                    <th>Nombre</th>
                    <th>Acciones</th>
                  </tr>
                </tfoot>
                <tbody>
        
                    {% for a in object_list %}
                        <tr>
                            <td>{{a.pk}}</td>
                            <td>{{a.clave}}</td>
                            <td>{{a.nombre}}</td>
                            <td>
                                <div class="dropdown mb-4">
                                    <button class="btn btn-danger dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Acciones
                                    </button>
                                    <div class="dropdown-menu animated--fade-in" aria-labelledby="dropdownMenuButton">
                                        <a class="dropdown-item" href="#"><i class="fas fa-fw fa-info-circle"></i>Editar</a>
                                        <a class="dropdown-item" href="#"><i class="fas fa-fw fa-pen-square"></i>Eliminar</a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>

{% include 'base/confirm_delete_modal.html' %}
{% endblock content %}

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
  <i class="fas fa-angle-up"></i>
</a>



{% block extrascripts %}
<!-- Page level plugins -->
<script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

<!-- Page level custom scripts -->
<script src="{% static 'js/demo/datatables-demo.js' %}"></script>

{% endblock extrascripts %}

templates/catalogos/materia_form.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}
{% block content %}

    <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Nueva Materia</h6>
        </div>
        <div class="card-body">
            <form  method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Guardar</button>
            </form>
        </div>
    </div>


{% endblock %}

templates/catalogos/materias_list.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
   Lista materias
{% endblock title %}
    

{% block extrahead %}
<link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock extrahead %}
    

        <!-- Page Heading -->
        
        {% block heading %}
        <div class="d-sm-flex align-items-center justify-content-between mb-4">
                <h1 class="h3 mb-2 text-gray-800">Catalogo de Materias</h1>
                <a href="{% url 'docente:materias_agregar' %}" class="d-none d-sm-inline-block btn btn-sm btn-success shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Nueva Materia</a>
        </div>
        {% endblock heading %}
            

        {% block content %}
    
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary"></h6>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Clave</th>
                    <th>Semestre</th>
                    <th>Programa</th>
                    <th>Acciones</th>
                  </tr>
                </thead>
                <tfoot>
                  <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Clave</th>
                    <th>Semestre</th>
                    <th>Programa</th>
                    <th>Acciones</th>
                  </tr>
                </tfoot>
                <tbody>
        
                    {% for a in object_list %}
                        <tr>
                            <td>{{a.pk}}</td>
                            <td>{{a.nombre}}</td>
                            <td>{{a.clave}}</td>
                            <td>{{a.semestre}}</td>
                            <td>{{ a.programa }}</td>
                            <td>
                                <div class="dropdown mb-4">
                                    <button class="btn btn-danger dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Acciones
                                    </button>
                                    <div class="dropdown-menu animated--fade-in" aria-labelledby="dropdownMenuButton">
                                        <a class="dropdown-item" href="#"><i class="fas fa-fw fa-info-circle"></i>Editar</a>
                                        <a class="dropdown-item" href="#"><i class="fas fa-fw fa-pen-square"></i>Eliminar</a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>

{% include 'base/confirm_delete_modal.html' %}
{% endblock content %}

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
  <i class="fas fa-angle-up"></i>
</a>



{% block extrascripts %}
<!-- Page level plugins -->
<script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

<!-- Page level custom scripts -->
<script src="{% static 'js/demo/datatables-demo.js' %}"></script>

{% endblock extrascripts %}