SAPDUAZ2/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apps.docente.views import Index
from django.contrib.auth.views import LogoutView

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('logout', LogoutView.as_view(), name='logout'),
                  path('docente/', include('apps.docente.urls', namespace='docente')),
                  path('nivel/', include('apps.nivel.urls', namespace='nivel')),
                  path('base/', include('apps.base.urls', namespace='base')),
                  path('index', Index.as_view(), name='index')
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/base/urls.py
from django.urls import path
from apps.base.views import base_list,nueva_base,docente_base_list


app_name='base'
urlpatterns = [
    path('listar',base_list,name='base_listar'),
    path('bases/nuevo/<id>',nueva_base,name='base_nueva'),
    path('historial/<id>',docente_base_list, name='historial_base'),
]

apps/docente/urls.py
from django.urls import path
from apps.docente import views

app_name = 'docente'
urlpatterns = [
    path('listar', views.ListaDocentes.as_view(), name='docente_listar'),
    path('activar/<id>', views.docente_activate, name='docente_activar'),
    path('nuevo/', views.NuevoDocente.as_view(), name='docente_nuevo'),
    path('gradonuevo/<id>', views.grado_academico_nuevo, name='grado_nuevo'),
    path('gradonuevo/', views.grado_academico_nuevo2, name='grado_nuevo2'),
    path('editar/<pk>', views.ActualizaDocente.as_view(), name='docente_editar'),
    path('detalles/<id>', views.docente_detalles, name='docente_detalles'),

    path('grados/listar', views.CatGradosList.as_view(), name='grados_listar'),
    path('incidencias/listar', views.CatIncidenciasList.as_view(), name='incidencias_listar'),
    path('cuerpos/listar', views.CuerpoList.as_view(), name='cuerpos_listar'),
    path('escuelas/listar', views.EscuelasList.as_view(), name='escuelas_listar'),
    path('materias/listar', views.MateriaList.as_view(), name='materias_listar'),
    path('programas/listar', views.ProgramaList.as_view(), name='programas_listar'),
    path('unidades/listar', views.UnidadAcademicaList.as_view(), name='unidades_listar'),

    path('grados/agregar', views.CatGradosCreate.as_view(), name='grados_agregar'),
    path('incidencias/agregar', views.CatIncidenciaCreate.as_view(), name='incidencias_agregar'),
    path('cuerpos/agregar', views.CuerpoCreate.as_view(), name='cuerpos_agregar'),
    path('escuelas/agregar', views.EscuelaCreate.as_view(), name='escuelas_agregar'),
    path('materias/agregar', views.MateriaCreate.as_view(), name='materias_agregar'),
    path('programas/agregar', views.ProgramaCreate.as_view(), name='programas_agregar'),
    path('unidades/agregar', views.UnidadAcademicaCreate.as_view(), name='unidades_agregar'),

]

apps/nivel/urls.py
from django.urls import path
from apps.nivel.views import nivel_list, BanderaList, BanderaCreate, CodificacionCreate, CodificacionList,nuevo_nivel,\
    docente_nivel_list


app_name='nivel'
urlpatterns = [
    path('listar',nivel_list,name='nivel_listar'),

    path('bandera/lista', BanderaList.as_view(),name='bandera_listar'),
    path('bandera/nueva',BanderaCreate.as_view(),name='bandera_agregar'),
    path('codificacion/lista', CodificacionList.as_view(), name='codificacion_listar'),
    path('codificacion/nueva', CodificacionCreate.as_view(), name='codificacion_agregar'),
    
    path('niveles/nuevo/<id>',nuevo_nivel,name='nivel_nuevo'),
    path('historial/<id>',docente_nivel_list, name='historial_nivel')
]

apps/docente/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, TemplateView, DetailView, CreateView, UpdateView

from apps.docente.forms import DatosPersonalesForm, DatosLaboralesForm, ConacytForm, ProdepForm, SniForm, \
    GradosAcademicosForm, CategoriaIncidenciasForm, CategoriaGradosForm, CuerpoAcademicoForm, \
    EscuelaForm, MateriaForm, ProgramaForm, UnidadAcademicaForm

from .models import DatosPersonales, DatosLaborales, GradosAcademicos, Conacyt, Prodep, Sni, \
    CategoriaIncidencias, CategoriaGrados, Escuela, UnidadAcademica, Programa, Materia, CuerpoAcademico


# Create your views here.

class Index(TemplateView):
    template_name = "base/base.html"


class ListaDocentes(ListView):
    model = DatosPersonales
    template_name = 'docente/lista_docente.html'


def docente_detalles(request, id):
    personales = DatosPersonales.objects.get(id=id)
    laborales = DatosLaborales.objects.get(id=id)

    grados = personales.gradosacademicos_set.all()
    conacyt = personales.conacyt_set.all()
    prodep = personales.prodep_set.all()
    sni = personales.sni_set.all()

    return render(request, 'docente/docente_detalles.html',
                  {
                      'personales': personales,
                      'laborales': laborales,
                      'grados': grados,
                      'conacyt': conacyt,
                      'prodep': prodep,
                      'sni': sni,
                  })


def docente_activate(request, id):
    docente = DatosPersonales.objects.get(id=id)
    if docente.status:
        docente.status = False
    else:
        docente.status = True

    docente.save()
    return redirect('docente:docente_listar')


class NuevoDocente(CreateView):
    model = DatosPersonales
    template_name = 'docente/docente_nuevo.html'
    form_class = DatosPersonalesForm
    laborales_form_class = DatosLaboralesForm
    conacyt_form_class = ConacytForm
    prodep_form_class = ProdepForm
    sni_form_class = SniForm

    success_url = reverse_lazy('docente:docente_listar')

    def get_context_data(self, **kwargs):
        context = super(NuevoDocente, self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class(self.request.GET)
        if 'form2' not in context:
            context['form2'] = self.laborales_form_class(self.request.GET)
        if 'form3' not in context:
            context['form3'] = self.conacyt_form_class(self.request.GET)
        if 'form4' not in context:
            context['form4'] = self.prodep_form_class(self.request.GET)
        if 'form5' not in context:
            context['form5'] = self.sni_form_class(self.request.GET)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object
        form = self.form_class(request.POST)
        form2 = self.laborales_form_class(request.POST)
        form3 = self.conacyt_form_class(request.POST)
        form4 = self.prodep_form_class(request.POST)
        form5 = self.sni_form_class(request.POST)
        if form.is_valid() and form2.is_valid() and form3.is_valid() and form4.is_valid() and form5.is_valid():
            personales = form.save()
            laborales = form2.save(commit=False)
            laborales.datos_personales = personales
            laborales.save()

            conacyt = form3.save(commit=False)
            conacyt.docente = personales
            conacyt.save()
            prodep = form4.save(commit=False)
            prodep.docente = personales
            prodep.save()
            sni = form5.save(commit=False)
            sni.docente = personales
            sni.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form, form2=form2,form3=form3,form4=form4,form5=form5))



class ActualizaDocente(UpdateView):
    template_name = 'docente/docente_editar.html'
    model = DatosLaborales
    form_class = DatosLaboralesForm
    extra_context = {'form_personales': DatosPersonalesForm()}
    success_url = reverse_lazy('lista_clientes')

    def form_valid(self, form):
        print('valid')
        laborales = self.get_object()
        form_personales= DatosPersonalesForm(self.request.POST, self.request.FILES, instance=laborales.datos_personales)
        if not form_personales.is_valid():
            return self.render_to_response(self.get_context_data(form=form, extra_context=form_personales))
        else:
            form_personales.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        form_personales = DatosPersonalesForm(self.request.POST, self.request.FILES, instance=self.get_object().datos_personales)
        return self.render_to_response(self.get_context_data(form=form, extra_context=form_personales))

    def get_context_data(self, **kwargs):
        if 'extra_context' in kwargs:
            form_personales = kwargs['extra_context']
            self.extra_context = kwargs['extra_context'] = {'form_personales': form_personales}
        return super().get_context_data(**kwargs)

    def get(self, request, *args, **kwargs):
        self.extra_context = {'form_personales': DatosPersonalesForm(instance=self.get_object().datos_personales)}
        return super().get(request, *args, **kwargs)

# class NuevoDocente(CreateView):
#     model = DatosPersonales
#     form_class = DatosPersonalesForm
#     extra_context = {
#         'laborales': DatosLaboralesForm(),
#         'cona': ConacytForm(),
#         'prod': ProdepForm(),
#         'sni': SniForm(),
#     }
#     template_name = 'docente/docente_nuevo.html'
#     success_url = reverse_lazy('docente:docente_listar')
#
#     def form_invalid(self, form):
#         form_laborales = DatosLaboralesForm(self.request.POST, self.request.FILES)
#         form_conacyt = ConacytForm(self.request.POST, self.request.FILES)
#         form_prodep = ProdepForm(self.request.POST, self.request.FILES)
#         form_sni = SniForm(self.request.POST, self.request.FILES)
#         return self.render_to_response(self.get_context_data(form=form, form_laborales=form_laborales,
#                                                              form_conacyt=form_conacyt,form_prodep=form_prodep,
#                                                              form_sni=form_sni))
#
#     def get_context_data(self, **kwargs):
#         if 'extra_context' in kwargs:
#             self.extra_context = {'cliente_form': kwargs['extra_context']}
#         return super().get_context_data(**kwargs)
#
#     def form_valid(self, form):
#         #form_personales = DatosPersonales(self.request.POST, self.request.FILES)
#         form_laborales = DatosLaboralesForm(self.request.POST, self.request.FILES)
#         form_conacyt = ConacytForm(self.request.POST, self.request.FILES)
#         form_prodep = ProdepForm(self.request.POST, self.request.FILES)
#         form_sni = SniForm(self.request.POST, self.request.FILES)
#         if form_laborales.is_valid() and form_conacyt.is_valid() and form_prodep.is_valid() and form_sni.is_valid():
#             personales = form.save()
#
#             laborales = form_laborales.save(commit=False)
#             laborales.datos_personales = personales
#             laborales.save()
#
#             conacyt = form_conacyt.save(commit=False)
#             conacyt.docente = personales
#             conacyt.save()
#             prodep = form_prodep.save(commit=False)
#             prodep.docente = personales
#             prodep.save()
#             sni = form_sni.save(commit=False)
#             sni.docente = personales
#             sni.save()
#
#             #return reverse_lazy('docente:docente_listar')
#
#         else:
#             return self.render_to_response(self.get_context_data(form=form, extra_context={'laborales':form_laborales,
#                                                                                            'cona':form_conacyt,
#                                                                                            'prod':form_prodep,
#                                                                                            'sni':form_sni}))
#         return super().form_valid(form)


# def docente_nuevo(request):
#     if request.method == 'POST':
#         form_personales = DatosPersonalesForm(request.POST)
#         form_laborales = DatosLaboralesForm(request.POST)
#         form_conacyt = ConacytForm(request.POST)
#         form_prodep = ProdepForm(request.POST)
#         form_sni = SniForm(request.POST)
#         if all([form_personales.is_valid(), form_laborales.is_valid(), form_conacyt.is_valid(), form_prodep.is_valid(),
#                 form_sni.is_valid()]):
#             personales = form_personales.save()
#
#             laborales = form_laborales.save(commit=False)
#             laborales.datos_personales = personales
#             laborales.save()
#
#             conacyt = form_conacyt.save(commit=False)
#             conacyt.docente = personales
#             conacyt.save()
#
#             prodep = form_prodep.save(commit=False)
#             prodep.docente = personales
#             prodep.save()
#
#             sni = form_sni.save(commit=False)
#             sni.docente = personales
#             sni.save()
#
#             return redirect('docente:docente_listar')
#         return redirect('docente:docente_listar')
#     else:
#         form_personales = DatosPersonalesForm()
#         form_laborales = DatosLaboralesForm()
#         form_conacyt = ConacytForm()
#         form_prodep = ProdepForm()
#         form_sni = SniForm()
#     return render(request, 'docente/docente_nuevo.html',
#                   {
#                       'personales': form_personales,
#                       'laborales': form_laborales,
#                       'cona': form_conacyt,

templates/docente/docente_detalles.html
{% extends 'base/base.html' %}
{% block content %}

<div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Detalles de {{ personales.nombres }} {{ personales.ap_paterno }} {{ personales.ap_materno }}</h6>
    </div>
    <h3>Datos Personales</h3>
    <hr>
    <div class="card-body">
        <label>Nombre</label>
        <p>{{ personales.nombres }}{{ personales.ap_paterno }}{{ personales.ap_materno }}</p>
        <label>Fecha de Nacimiento</label>
        <p>{{ personales.fecha_nacimiento }}</p>
        <label>RFC</label>
        <p>{{ personales.rfc }}</p>
        <label>CURP</label>
        <p>{{ personales.curp }}</p>
        <label>Numero de Seguro Social</label>
        <p>{{ personales.nss }}</p>
        <label>Sexo</label>
        <p>{{ personales.sexo }}</p>
        <label>Estado civil</label>
        <p>{{ personales.estado_civil }}</p>
        <label>Domicilio</label>
        <p>{{ personales.domicilio }}</p>
        <label>Municipio</label>
        <p>{{ personales.municipio }}</p>
        <label>Estatus del docente</label>
        <p>{% if docente.status %}
            Activo
            {% else %}
            Inactivo
            {% endif %}
        </p>
    </div>
    <h3>Datos Laborales</h3>
    <hr>
    <div class="card-body">
        <label>Matricula de Docente</label>
        <p>{{ laborales.matricula_docente }}</p>
        <label>Matricula de Nómina</label>
        <p>{{ laborales.matricula_nomina }}</p>
        <label>Fecha de ingreso</label>
        <p>{{ laborales.fecha_ingreso }}</p>
        <label>Numero de expediente</label>
        <p>{{ laborales.no_expediente }}</p>
        <label>Exclusividad con la UAZ</label>
        {% if laborales.exclusivo %}
            <p>Es exclusivo</p>
            {% else %}
            <p>No es exclusivo</p>
            <label>Observaciones de exclusividad</label>
            <p>{{ laborales.observaciones_exc }}</p>
            {% endif %}

        <label>Observaciones de exclusividad</label>
        <p>{{ laborales.observaciones_exc }}</p>
        <label>CVU</label>
        <p>{{ laborales.cvu }}</p>
        <label>Cuerpo Academico</label>
        <p>{{ laborales.cuerpo_academico }}</p>
        <label>Observaciones Cuerpo Academico</label>
        <p>{{ laborales.observaciones_c_a }}</p>
        <label>Programa</label>
        <p>{{ laborales.programa }}</p>
        <label>Perfil</label>
        <p>Perfil</p>
    </div>
    <h3>Conacyt</h3>
    <hr>
    <div class="card-body">
        {% for con in conacyt %}
            <div>
                <p>{{ con.numero_proyecto }}</p>
                <p>{{ con.nombre_proyecto }}</p>
                <p>{{ con.fecha_inicio }}</p>
                <p>{{ con.fecha_fin }}</p>
            </div>
        {% endfor %}
    </div>
    <h3>Prodep</h3>
    <hr>
    <div class="card-body">
        {% for pro in prodep %}
            <div>
                <p>{{ pro.clave }}</p>
                <p>{{ pro.descripcion }}</p>
                <p>{{ pro.fecha_inicio }}</p>
                <p>{{ pro.fecha_fin }}</p>
                <p>{{ pro.imagen_prodep }}</p>
            </div>
        {% endfor %}
    </div>
    <h3>Sni</h3>
    <hr>
    <div class="card-body">
        {% for s in sni %}
            <div>
                <p>{{ s.clave }}</p>
                <p>{{ s.descripcion }}</p>
                <p>{{ s.fecha_inicio }}</p>
                <p>{{ s.fecha_fin }}</p>
                <p>{{ s.nivel }}</p>
                <p><a href="{{ MEDIA_URL }}{{ s.imagen_sni }}">{{ s.imagen_sni }}</a></p>
            </div>
        {% endfor %}
    </div>


    <h3>Grados Academicos</h3>
    <hr>
    <div class="card-body">
        <button class="btn btn-success" href="{% url 'docente:grado_nuevo' personales.pk %}"><i class="fas fa-fw fa-upload"></i> Agregar grado academico</button>
        <p></p>
        
        <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                        <th>ID</th>
                        <th>Escuela</th>
                        <th>Fecha obtencion</th>
                        <th>Categoria Grados</th>
                        <th>Nombre Estudio</th>
                        <th>Cedula</th>
                        <th>Acciones</th>
                    </tr>
                  </thead>
                  <tfoot>
                    <tr>
                        <th>ID</th>
                        <th>Escuela</th>
                        <th>Fecha obtencion</th>
                        <th>Categoria Grados</th>
                        <th>Nombre Estudio</th>
                        <th>Cedula</th>
                        <th>Acciones</th>
                    </tr>
                  </tfoot>
                  <tbody>
          
                      {% for grado in grados %}
                          <tr>
                              <td>{{grado.id}}</td>
                              <td>{{grado.escuela}}</td>
                              <td>{{grado.fecha_obtencion}}</td>
                              <td>{{grado.categoria_grados}}</td>
                              <td>{{grado.nombre_estudio}}</td>
                              <td>{{grado.cedula}}</td>
                              <td>
                                <div class="dropdown mb-4">
                                    <button class="btn btn-danger dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Acciones
                                    </button>
                                    <div class="dropdown-menu animated--fade-in" aria-labelledby="dropdownMenuButton">
                                        <a class="dropdown-item" href="#"><i class="fas fa-fw fa-info-circle"></i>Editar</a>
                                        <a class="dropdown-item" href="#"><i class="fas fa-fw fa-pen-square"></i>Eliminar</a>
                                    </div>
                                </div>
                            </td>
                          </tr>
                      {% endfor %}
                  </tbody>
                </table>
        </div>

    </div>

</div>


{% endblock %}

templates/docente/docente_editar.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}
{% block content %}

    <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Editar Docente</h6>
        </div>
        <div class="card-body">
            <form method="post" class="form" enctype="multipart/form-data">
                {% csrf_token %}
                Datos Personales
                {{ form_personales.as_p }}
                Datos Laborales
                {{ form.as_p }}

                <button type="submit" class="btn btn-primary">Guardar</button>
            </form>
        </div>
    </div>


{% endblock %}

templates/docente/docente_nuevo.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}

{% block extrahead %}
    {# Include FontAwesome; required for icon display #}
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.css">

    {# Include Bootstrap 4 and jQuery #}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    {# Django Tempus Dominus assets are included in `{{ form.media }}` #}
    {{ form.media }}
{% endblock %}
{% block content %}

    <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Nuevo Docente</h6>
        </div>
        <div class="card-body">
            <form method="post" class="form" enctype="multipart/form-data">
                {% csrf_token %}

                Datos Personales
{#                {% if form.errors %}#}
{#                {{ form.errors }}#}
{#                {% endif %} #}
                {{ form.as_p }}

                Datos Laborales
{#                {% if form2.errors %}#}
{#                {{ form2.errors }}#}
{#                {% endif %}#}
                {{ form2.as_p }}

                Datos Conacyt
{#                {% if form3.errors %}#}
{#                {{ form3.errors }}#}
{#                {% endif %}#}
                {{ form3.as_p }}

                Datos Prodep
{#                {% if form4.errors %}#}
{#                {{ form4.errors }}#}
{#                {% endif %}#}
{#                {% if form.errors %}#}
{#                    <div class="alert alert-warning alert-dismissible fade show" role="alert">#}
{#                        {{form.errors}}#}
{#                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">#}
{#                            <span aria-hidden="true">&times;</span>#}
{#                        </button>#}
{#                    </div>#}
{#                {% endif %}#}
                {{ form4.as_p }}

                Datos SNI
{#                {% if form4.errors %}#}
{#                {{ form5.errors }}#}
{#                {% endif %}#}
                {{ form5.as_p }}
{#                {% for campo in personales %}#}
{#                    <th class="col-sm">#}
{#                            {% render_field campo class="form-control" %}#}
{#                    </th>#}
{#                {% endfor %}#}
{#                {% for campo in laborales %}#}
{#                    <th class="col-sm">#}
{#                            {% render_field campo class="form-control" %}#}
{#                    </th>#}
{#                {% endfor %}#}
                <button type="submit" class="btn btn-primary">Agregar</button>
            </form>
        </div>
    </div>


{% endblock %}

templates/docente/grado_academico_form.html
{% extends 'base/base.html' %}
{% load widget_tweaks %}

{% block extrahead %}
    {# Include FontAwesome; required for icon display #}
    <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.css">

    {# Include Bootstrap 4 and jQuery #}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    {# Django Tempus Dominus assets are included in `{{ form.media }}` #}
    {{ form_grado.media }}
{% endblock %}

{% block content %}

    <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">Nuevo grado academico para el docente {{ docente }}</h6>
        </div>
        <div class="card-body" >
            <form method="post" class="form" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form_grado.as_p }}

                <button type="submit" class="btn btn-primary">Guardar</button>
            </form>
        </div>
    </div>

{% endblock %}

templates/docente/lista_docente.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
   Lista Docentes 
{% endblock title %}
    

{% block extrahead %}
<link href="{% static 'vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">
{% endblock extrahead %}
    

        <!-- Page Heading -->
        
        {% block heading %}
        <h1 class="h3 mb-2 text-gray-800">Lista de Docentes</h1>
        <p class="mb-4">Descripcion</p>

        {% endblock heading %}
            

        {% block content %}
    
        <!-- DataTales Example -->
        <div class="card shadow mb-4">
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary"></h6>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>RFC</th>
                    <th>CURP</th>
                    <th>NSS</th>
                    <th>Status</th>
                    <th>Acciones</th>
                  </tr>
                </thead>
                <tfoot>
                  <tr>
                    <th>Name</th>
                    <th>Nombre</th>
                    <th>RFC</th>
                    <th>CURP</th>
                    <th>NSS</th>
                    <th>Status</th>
                    <th>Acciones</th>
                  </tr>
                </tfoot>
                <tbody>
        
                    {% for docente in object_list %}
                        <tr>
                            <td>{{docente.id}}</td>
                            <td>{{docente.nombres}} {{docente.ap_paterno}} {{docente.ap_materno}}</td>
                            <td>{{docente.rfc}}</td>
                            <td>{{docente.curp}}</td>
                            <td>{{docente.nss}}</td>
                            <th>{% if docente.status %}
                                Activo
                                {% else %}
                                Inactivo
                                {% endif %}
                            </th>
                            <td>
                                <div class="dropdown mb-4">
                                    <button class="btn btn-danger dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Acciones
                                    </button>
                                    <div class="dropdown-menu animated--fade-in" aria-labelledby="dropdownMenuButton">
                                        <a class="dropdown-item" href="{% url 'docente:docente_detalles' docente.pk %}"><i class="fas fa-fw fa-info-circle"></i>Perfil Completo</a>
                                        <a class="dropdown-item" href="{% url 'docente:docente_editar' docente.pk %}"><i class="fas fa-fw fa-pen-square"></i>Editar</a>
                                        <a  class="dropdown-item confirm-delete" href="{% url 'docente:docente_activar' docente.pk %}" title="Delete" data-toggle="modal" data-target="#confirmDeleteModal" id="deleteButton{{docente.pk}}">

                                            {% if docente.status %}
                                                <i class="fas fa-fw fa-times"></i>Desactivar
                                            {% else %}
                                                <i class="fas fa-fw fa-check"></i>Activar
                                            {% endif %}
                                        </a>

                                        <a class="dropdown-item" href="#"><i class="fas fa-fw fa-user-clock"></i>Ver Interrupciones</a>
                                        <a class="dropdown-item" href="{% url 'docente:grado_nuevo' docente.pk %}"><i class="fas fa-fw fa-folder-plus"></i>Agregar Grado Académico</a>
                                        <a class="dropdown-item" href="{% url 'base:base_nueva' docente.pk %}"><i class="fas fa-fw fa-history"></i>Actualizar Base</a>
                                        <a class="dropdown-item" href="{% url 'nivel:nivel_nuevo' docente.pk %}"><i class="fas fa-fw fa-history"></i>Actualizar nivel</a>
                                    </div>
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>

{% include 'base/confirm_delete_modal.html' %}
{% endblock content %}

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
  <i class="fas fa-angle-up"></i>
</a>



{% block extrascripts %}
<!-- Page level plugins -->
<script src="{% static 'vendor/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

<!-- Page level custom scripts -->
<script src="{% static 'js/demo/datatables-demo.js' %}"></script>

{% endblock extrascripts %}